name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]   # or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # First: Node.js build
  node-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build with Node.js
        run: npm run build

      - name: Upload Node build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-dist
          path: dist    # 👈 change this if your output folder is different

  # Second: Jekyll build using Node output
  jekyll-build:
    runs-on: ubuntu-latest
    needs: node-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Node build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-dist
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist          # 👈 make Jekyll use the Node build folder
          destination: ./_site

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3

  # Third: Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: jekyll-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
